#!/usr/bin/env bash
#
# pkgconvert - Universal Linux package converter with pre-flight analysis
# https://github.com/  (add your repo link here)
#
#   Inputs:   .deb  .rpm  .tar(.gz/.xz/.bz2/.zst)  .AppImage  .snap
#   Outputs:  tar.gz | deb | rpm | dir (plain folder)
#
# Before converting, the script ANALYZES the package against your chosen
# output format and warns about things that may cause problems:
#   - dependencies, translated between Debian / Fedora / openSUSE / Arch names
#   - shared libraries the app's binaries need that are MISSING on this system
#   - install/remove scripts that will not be carried over
#   - systemd services and desktop launchers that need manual steps
#
# Usage:
#   ./pkgconvert.sh app.deb                        # interactive
#   ./pkgconvert.sh app.deb --to rpm               # analyze, confirm, convert
#   ./pkgconvert.sh app.deb --to rpm --yes         # skip confirmation
#   ./pkgconvert.sh app.deb --info                 # analysis only
#   ./pkgconvert.sh app.deb --to rpm --distro opensuse   # force target distro
#
# Note: this REPACKAGES binaries; it does not recompile them.

set -euo pipefail

VERSION="1.0.0"

QUIET=0

# Exit codes: 1 general, 2 bad arguments, 3 missing tool, 4 extraction failed, 5 build failed
code_desc() {
  case "$1" in
    2) echo "invalid arguments or input file" ;;
    3) echo "missing required tool" ;;
    4) echo "extraction failed" ;;
    5) echo "build failed" ;;
    *) echo "general error" ;;
  esac
}

err() {  # err [-c CODE] message
  local code=1
  if [ "${1:-}" = "-c" ]; then code="$2"; shift 2; fi
  echo "Error: $*" >&2
  LAST_EXIT_CODE="$code"
  offer_failure_report "$*"
  echo "Exit code: $code ($(code_desc "$code"))" >&2
  exit "$code"
}
note() { echo ">> $*"; }
need() { command -v "$1" >/dev/null || err -c 3 "'$1' is required. Install package '$2' with your package manager (dnf/apt/zypper/pacman)."; }

# ---------------- failure reports ----------------
# On failure after analysis has run, offer to save a Markdown log of the
# failed attempt (auto-saved if --report was given). Helps users keep a
# record and makes for great GitHub bug reports.
ANALYSIS_DONE=0
AUTO_REPORT=0

generate_failure_report() {  # $1 = output path, $2 = error message
  {
    echo "# pkgconvert — failed conversion report"
    echo
    echo "- **pkgconvert version:** ${VERSION:-unknown}"
    echo "- **Exit code:** ${LAST_EXIT_CODE:-1} ($(code_desc "${LAST_EXIT_CODE:-1}"))"
    echo "- **Date:** $(date -u '+%Y-%m-%d %H:%M UTC')"
    echo "- **Host distro:** ${HOST_DISTRO:-unknown} ($(uname -srm))"
    echo "- **Input file:** \`$(basename "${INPUT:-?}")\` (${INFMT:-unknown} format)"
    echo "- **Requested output:** ${OUTFMT:-not chosen} (dependency names: ${TARGET_DISTRO:-n/a})"
    echo
    echo "## Error"
    echo
    echo '```'
    echo "$2"
    echo '```'
    echo
    echo "## Package metadata"
    echo
    echo "- Name: ${PKGNAME:-unknown}"
    echo "- Version: ${PKGVER:-unknown}"
    echo "- Architecture: ${PKGARCH:-unknown}"
    if [ -n "${DEPS:-}" ]; then
      echo "- Declared dependencies: $DEPS"
    fi
    [ -n "${HAS_SCRIPTS:-}" ] && echo "- Install/remove scripts: $HAS_SCRIPTS"
    echo
    echo "## Tool availability on this system"
    echo
    for t in ar tar cpio rpm2cpio rpmbuild dpkg-deb unsquashfs zstd readelf; do
      if command -v "$t" >/dev/null; then echo "- $t: available"; else echo "- $t: MISSING"; fi
    done
    echo
    echo "## Reproduce"
    echo
    echo '```'
    echo "./pkgconvert.sh $(basename "${INPUT:-file}") --to ${OUTFMT:-<format>} --info"
    echo '```'
    echo
    echo "_Generated by pkgconvert. If you believe this failure is a bug,_"
    echo "_attach this file to an issue on the project's GitHub page._"
  } > "$1"
}

offer_failure_report() {
  # Only after analysis; skip when non-interactive unless --report was given
  [ "${ANALYSIS_DONE:-0}" = 1 ] || return 0
  local default="pkgconvert-failure-$(date +%Y%m%d-%H%M%S).md"
  local dest=""
  if [ "$AUTO_REPORT" = 1 ]; then
    dest="$default"
  elif [ -t 0 ]; then
    read -rp "Generate a Markdown report of this failed attempt? [y/N] " ans
    case "${ans:-n}" in
      y|Y|yes|YES)
        read -rp "Save to [$default]: " dest
        dest="${dest:-$default}" ;;
      *) return 0 ;;
    esac
  else
    return 0
  fi
  if generate_failure_report "$dest" "$1" 2>/dev/null; then
    echo "Failure report saved: $dest" >&2
  fi
}

# ---------------- args ----------------
case "${1:-}" in --version|-V) echo "pkgconvert $VERSION"; exit 0 ;; esac
[ $# -ge 1 ] || err -c 2 "Usage: $0 <package-file> [--to tar.gz|deb|rpm|dir] [--distro debian|fedora|opensuse|arch] [--name N] [--version V] [--arch A] [--quiet] [--yes] [--report] [--info]"

INPUT="$1"; shift
OUTFMT=""; PKGNAME=""; PKGVER=""; PKGARCH=""; INFOONLY=0; ASSUME_YES=0; TARGET_DISTRO=""
while [ $# -gt 0 ]; do
  case "$1" in
    --to)      OUTFMT="$2"; shift 2 ;;
    --distro)  TARGET_DISTRO="$2"; shift 2 ;;
    --name)    PKGNAME="$2"; shift 2 ;;
    --version) PKGVER="$2"; shift 2 ;;
    --arch)    PKGARCH="$2"; shift 2 ;;
    --yes|-y)  ASSUME_YES=1; shift ;;
    --quiet|-q) QUIET=1; shift ;;
    --report)  AUTO_REPORT=1; shift ;;
    --info)    INFOONLY=1; shift ;;
    *) err -c 2 "Unknown option: $1" ;;
  esac
done

[ -f "$INPUT" ] || err -c 2 "File not found: $INPUT"

WORKDIR="$(mktemp -d)"
STAGE="$WORKDIR/root"
mkdir -p "$STAGE"
trap 'rm -rf "$WORKDIR"' EXIT

DESC="Converted with pkgconvert"
DEPS=""
HAS_SCRIPTS=""

# ---------------- distro detection ----------------
detect_distro() {
  local id="" like=""
  if [ -r /etc/os-release ]; then
    id="$(. /etc/os-release; echo "${ID:-}")"
    like="$(. /etc/os-release; echo "${ID_LIKE:-}")"
  fi
  case "$id $like" in
    *arch*|*manjaro*|*endeavouros*)          echo arch ;;
    *suse*)                                  echo opensuse ;;
    *fedora*|*rhel*|*centos*|*nobara*)       echo fedora ;;
    *debian*|*ubuntu*|*mint*|*pop*)          echo debian ;;
    *)                                       echo unknown ;;
  esac
}
HOST_DISTRO="$(detect_distro)"

# ---------------- detect input type ----------------
lc="$(echo "$INPUT" | tr 'A-Z' 'a-z')"
case "$lc" in
  *.deb)                          INFMT="deb" ;;
  *.rpm)                          INFMT="rpm" ;;
  *.appimage)                     INFMT="appimage" ;;
  *.snap)                         INFMT="snap" ;;
  *.tar.gz|*.tgz|*.tar.xz|*.tar.bz2|*.tar.zst|*.tar) INFMT="tar" ;;
  *) err -c 2 "Unrecognized input type. Supported: .deb .rpm .tar.* .AppImage .snap" ;;
esac
note "Input format: $INFMT   (host distro: $HOST_DISTRO)"

# ---------------- extract input -> STAGE ----------------
extract_deb() {
  need ar binutils
  local abs; abs="$(readlink -f "$INPUT")"
  ( cd "$WORKDIR" && ar x "$abs" )
  local data ctrl
  data="$(find "$WORKDIR" -maxdepth 1 -name 'data.tar.*' | head -n1)"
  ctrl="$(find "$WORKDIR" -maxdepth 1 -name 'control.tar.*' | head -n1)"
  [ -n "$data" ] || err -c 4 "No data.tar inside .deb"
  case "$data" in *.zst) need zstd zstd ;; esac
  tar -xf "$data" -C "$STAGE"
  if [ -n "$ctrl" ]; then
    mkdir -p "$WORKDIR/ctrl"; tar -xf "$ctrl" -C "$WORKDIR/ctrl"
    local c="$WORKDIR/ctrl/control"
    if [ -f "$c" ]; then
      PKGNAME="${PKGNAME:-$(grep -m1 '^Package:' "$c" | cut -d' ' -f2-)}"
      PKGVER="${PKGVER:-$(grep -m1 '^Version:' "$c" | cut -d' ' -f2-)}"
      PKGARCH="${PKGARCH:-$(grep -m1 '^Architecture:' "$c" | cut -d' ' -f2-)}"
      DESC="$(grep -m1 '^Description:' "$c" | cut -d' ' -f2- || true)"
      DEPS="$(grep -m1 '^Depends:' "$c" | cut -d' ' -f2- || true)"
    fi
    HAS_SCRIPTS="$(cd "$WORKDIR/ctrl" && ls preinst postinst prerm postrm 2>/dev/null | tr '\n' ' ' || true)"
  fi
}

extract_rpm() {
  need rpm2cpio rpm
  need cpio cpio
  local abs; abs="$(readlink -f "$INPUT")"
  ( cd "$STAGE" && rpm2cpio "$abs" | cpio -idm --quiet )
  if command -v rpm >/dev/null; then
    PKGNAME="${PKGNAME:-$(rpm -qp --qf '%{NAME}' "$abs" 2>/dev/null || true)}"
    PKGVER="${PKGVER:-$(rpm -qp --qf '%{VERSION}' "$abs" 2>/dev/null || true)}"
    PKGARCH="${PKGARCH:-$(rpm -qp --qf '%{ARCH}' "$abs" 2>/dev/null || true)}"
    DESC="$(rpm -qp --qf '%{SUMMARY}' "$abs" 2>/dev/null || echo "$DESC")"
    DEPS="$(rpm -qpR "$abs" 2>/dev/null | grep -v '^rpmlib(' | tr '\n' ',' || true)"
    local s; s="$(rpm -qp --scripts "$abs" 2>/dev/null || true)"
    [ -n "$s" ] && HAS_SCRIPTS="rpm scriptlets"
  fi
}

extract_tar() {
  case "$lc" in *.tar.zst) need zstd zstd ;; esac
  tar -xf "$INPUT" -C "$STAGE"
}

extract_appimage() {
  chmod +x "$INPUT" 2>/dev/null || true
  local abs; abs="$(readlink -f "$INPUT")"
  if ( cd "$WORKDIR" && "$abs" --appimage-extract >/dev/null 2>&1 ); then
    mv "$WORKDIR/squashfs-root/"* "$STAGE"/
  else
    need unsquashfs squashfs-tools
    unsquashfs -q -d "$WORKDIR/sq" "$abs" >/dev/null 2>&1 || err -c 4 "Could not extract AppImage"
    mv "$WORKDIR/sq/"* "$STAGE"/
  fi
}

extract_snap() {
  need unsquashfs squashfs-tools
  unsquashfs -q -d "$WORKDIR/sq" "$INPUT" >/dev/null 2>&1 || err -c 4 "Could not extract snap"
  mv "$WORKDIR/sq/"* "$STAGE"/
}

case "$INFMT" in
  deb)      extract_deb ;;
  rpm)      extract_rpm ;;
  tar)      extract_tar ;;
  appimage) extract_appimage ;;
  snap)     extract_snap ;;
esac

# Fill metadata gaps from the filename (e.g. myapp-1.2.3.rpm)
base="$(basename "$INPUT")"; base="${base%.*}"
PKGNAME="${PKGNAME:-$(echo "$base" | sed 's/[-_][0-9].*//')}"
PKGNAME="${PKGNAME:-convertedapp}"
PKGVER="${PKGVER:-$(echo "$base" | grep -oE '[0-9]+(\.[0-9]+)+' | head -n1)}"
PKGVER="${PKGVER:-1.0}"
PKGARCH="${PKGARCH:-$(uname -m)}"

echo
echo "==== Package info ===="
echo "  Name:    $PKGNAME"
echo "  Version: $PKGVER"
echo "  Arch:    $PKGARCH"
echo "  Files:   $(find "$STAGE" -type f | wc -l)"
echo

# ---------------- choose output format ----------------
if [ -z "$OUTFMT" ] && [ "$INFOONLY" = 0 ]; then
  echo "Convert to which format?"
  echo "  1) tar.gz  - portable archive"
  echo "  2) deb     - Debian/Ubuntu package"
  echo "  3) rpm     - Fedora/RHEL/openSUSE package"
  echo "  4) dir     - plain extracted folder"
  read -rp "Choice [1-4]: " c
  case "$c" in
    1) OUTFMT="tar.gz" ;; 2) OUTFMT="deb" ;; 3) OUTFMT="rpm" ;; 4) OUTFMT="dir" ;;
    *) err -c 2 "Invalid choice" ;;
  esac
  read -rp "Skip the beginner explanations? (warnings and errors always show) [y/N] " sq
  case "${sq:-n}" in y|Y|yes|YES) QUIET=1 ;; esac
fi

# Pick the distro whose package names we translate dependencies INTO:
# explicit --distro wins; else deb output implies debian; rpm output uses the
# host distro if it's an rpm family, otherwise fedora; else just the host.
if [ -z "$TARGET_DISTRO" ]; then
  case "$OUTFMT" in
    deb) TARGET_DISTRO="debian" ;;
    rpm) case "$HOST_DISTRO" in opensuse) TARGET_DISTRO="opensuse" ;; *) TARGET_DISTRO="fedora" ;; esac ;;
    *)   TARGET_DISTRO="$HOST_DISTRO" ;;
  esac
fi
case "$TARGET_DISTRO" in debian|fedora|opensuse|arch|unknown) ;; *) err -c 2 "--distro must be debian, fedora, opensuse, or arch" ;; esac

# =====================================================================
#                        PRE-FLIGHT ANALYSIS
# =====================================================================

# Dependency name translations: debian|fedora|opensuse|arch
# "-" means no direct single-package equivalent is known.
DEP_MAP="
libc6|glibc|glibc|glibc
libstdc++6|libstdc++|libstdc++6|gcc-libs
libgcc-s1|libgcc|libgcc_s1|gcc-libs
libatomic1|libatomic|libatomic1|gcc-libs
libgtk-3-0|gtk3|libgtk-3-0|gtk3
libgtk-4-1|gtk4|libgtk-4-1|gtk4
libx11-6|libX11|libX11-6|libx11
libxcb1|libxcb|libxcb1|libxcb
libxss1|libXScrnSaver|libXss1|libxss
libxtst6|libXtst|libXtst6|libxtst
libxrandr2|libXrandr|libXrandr2|libxrandr
libxdamage1|libXdamage|libXdamage1|libxdamage
libxcomposite1|libXcomposite|libXcomposite1|libxcomposite
libnss3|nss|mozilla-nss|nss
libnspr4|nspr|mozilla-nspr|nspr
libasound2|alsa-lib|alsa|alsa-lib
libpulse0|pulseaudio-libs|libpulse0|libpulse
libnotify4|libnotify|libnotify4|libnotify
libsecret-1-0|libsecret|libsecret-1-0|libsecret
libuuid1|libuuid|libuuid1|util-linux-libs
libssl3|openssl-libs|libopenssl3|openssl
libcurl4|libcurl|libcurl4|curl
libexpat1|expat|libexpat1|expat
libfontconfig1|fontconfig|fontconfig|fontconfig
libfreetype6|freetype|libfreetype6|freetype2
libpango-1.0-0|pango|libpango-1_0-0|pango
libcairo2|cairo|libcairo2|cairo
libdbus-1-3|dbus-libs|libdbus-1-3|dbus
libgbm1|mesa-libgbm|libgbm1|mesa
libdrm2|libdrm|libdrm2|libdrm
libgl1|mesa-libGL|Mesa-libGL1|mesa
libvulkan1|vulkan-loader|libvulkan1|vulkan-icd-loader
libayatana-appindicator3-1|libappindicator-gtk3|libappindicator3-1|libappindicator-gtk3
libudev1|systemd-libs|libudev1|systemd-libs
libatk1.0-0|atk|libatk-1_0-0|at-spi2-core
libglib2.0-0|glib2|libglib-2_0-0|glib2
"

col_for() {  # distro -> column number in DEP_MAP
  case "$1" in debian) echo 1 ;; fedora) echo 2 ;; opensuse) echo 3 ;; arch) echo 4 ;; *) echo 0 ;; esac
}

# Build a hash index once: any known name -> row number (O(1) lookups
# instead of re-scanning the whole table for every dependency)
declare -A DEP_IDX
declare -a ROW_D ROW_F ROW_S ROW_A
_i=0
while IFS='|' read -r _d _f _s _a; do
  [ -z "$_d" ] && continue
  ROW_D[$_i]="$_d"; ROW_F[$_i]="$_f"; ROW_S[$_i]="$_s"; ROW_A[$_i]="$_a"
  DEP_IDX["$_d"]=$_i; DEP_IDX["$_f"]=$_i; DEP_IDX["$_s"]=$_i; DEP_IDX["$_a"]=$_i
  _i=$((_i+1))
done <<< "$DEP_MAP"
unset _i _d _f _s _a

map_dep() {  # map_dep <name> <target-distro>: O(1) hash lookup
  local idx="${DEP_IDX[$1]:-}" tcol
  tcol="$(col_for "$2")"
  { [ -n "$idx" ] && [ "$tcol" != 0 ]; } || { echo ""; return; }
  case "$tcol" in
    1) echo "${ROW_D[$idx]}" ;; 2) echo "${ROW_F[$idx]}" ;;
    3) echo "${ROW_S[$idx]}" ;; 4) echo "${ROW_A[$idx]}" ;;
  esac
}

# Per-distro command hints
case "$TARGET_DISTRO" in
  debian)   SEARCH_CMD="apt search";    PROVIDES_CMD="apt-file search libname.so.X   (apt install apt-file first)" ;;
  fedora)   SEARCH_CMD="dnf search";    PROVIDES_CMD="dnf provides '*/libname.so.X'" ;;
  opensuse) SEARCH_CMD="zypper search"; PROVIDES_CMD="zypper what-provides 'libname.so.X'" ;;
  arch)     SEARCH_CMD="pacman -Ss";    PROVIDES_CMD="pkgfile libname.so.X   (pacman -S pkgfile first)" ;;
  *)        SEARCH_CMD="your package manager's search"; PROVIDES_CMD="your package manager's file-provides search" ;;
esac

WARN_COUNT=0
warn() { WARN_COUNT=$((WARN_COUNT+1)); echo "  [!] $*"; }
info() { [ "$QUIET" = 1 ] && return 0; echo "  [i] $*"; }

echo "==== Pre-flight analysis (target: ${OUTFMT:-info}, distro names: $TARGET_DISTRO) ===="

# --- 1. Declared dependencies ---
if [ -n "$DEPS" ]; then
  echo
  echo "  Declared dependencies (translated to $TARGET_DISTRO names):"
  while read -r dep; do
    case "$dep" in /*|*.so*) continue ;; esac
    m="$(map_dep "$dep" "$TARGET_DISTRO")"
    if [ -n "$m" ] && [ "$m" != "-" ]; then
      echo "      $dep  ->  $m"
    else
      echo "      $dep  ->  (unknown; try: $SEARCH_CMD ${dep#lib})"
    fi
  done < <(echo "$DEPS" | tr ',' '\n' | sed 's/([^)]*)//g; s/|.*//; s/^ *//; s/ *$//' | grep -v '^$' | sort -u)
  if [ "$OUTFMT" = "rpm" ] || [ "$OUTFMT" = "deb" ]; then
    warn "Dependency names will NOT be embedded in the converted package."
    info "Install the right-hand equivalents above if the app fails to start."
  fi
else
  echo
  info "No dependency metadata found (normal for tar/AppImage inputs)."
fi

# --- 2. Scan actual binaries for shared libraries missing on THIS system ---
if command -v readelf >/dev/null && command -v ldconfig >/dev/null; then
  echo
  echo "  Scanning binaries for required shared libraries..."
  SYSLIBS="$WORKDIR/syslibs"; ldconfig -p 2>/dev/null | awk '{print $1}' > "$SYSLIBS" || true
  NEEDED="$WORKDIR/needed"
  # Parallel scan: fan the ELF check + readelf across all CPU cores.
  # Big Electron/Qt apps have hundreds of binaries; this is ~Nx faster.
  NPROC="$(nproc 2>/dev/null || echo 2)"
  find "$STAGE" -type f 2>/dev/null | head -n 4000 | \
    xargs -d '\n' -P "$NPROC" -n 24 bash -c '
      for f in "$@"; do
        [ "$(head -c4 "$f" 2>/dev/null | tr -d "\0")" = $'"'"'\x7fELF'"'"' ] || continue
        readelf -d "$f" 2>/dev/null | awk "/NEEDED/ {gsub(/[\[\]]/,\"\",\$NF); print \$NF}"
      done' _ 2>/dev/null | sort -u | head -n 300 > "$NEEDED"
  BUNDLED="$WORKDIR/bundled"
  find "$STAGE" -type f \( -name '*.so' -o -name '*.so.*' \) -printf '%f\n' 2>/dev/null | sort -u > "$BUNDLED" || : > "$BUNDLED"
  MISS=0
  while read -r lib; do
    [ -z "$lib" ] && continue
    grep -qxF "$lib" "$BUNDLED" && continue
    grep -qF "$lib" "$SYSLIBS" && continue
    MISS=$((MISS+1))
    [ "$MISS" -le 15 ] && echo "      missing on this system: $lib"
  done < "$NEEDED"
  if [ "${MISS:-0}" -gt 0 ]; then
    warn "$MISS shared librar$( [ "$MISS" = 1 ] && echo y || echo ies) not found on this machine (first 15 shown)."
    info "Find the providing package:  $PROVIDES_CMD"
  else
    echo "      All required libraries are either bundled or already installed here."
  fi
else
  echo
  info "Skipped binary scan (needs 'readelf' from binutils and 'ldconfig')."
fi

# --- 3. Things that don't survive conversion ---
echo
if [ -n "$HAS_SCRIPTS" ]; then
  warn "Package has install/remove scripts ($HAS_SCRIPTS)."
  info "These will NOT run or be carried over. Apps that create users, set"
  info "permissions, or register services in these scripts may need manual setup."
fi
UNITS="$(find "$STAGE" -path '*systemd*' -name '*.service' -o -path '*systemd*' -name '*.timer' 2>/dev/null | head -n5 || true)"
if [ -n "$UNITS" ]; then
  warn "Contains systemd service files:"
  echo "$UNITS" | sed "s|$STAGE|      |"
  info "After installing, enable manually: sudo systemctl daemon-reload && sudo systemctl enable <name>"
fi
DESKTOP="$(find "$STAGE" -name '*.desktop' 2>/dev/null | head -n3 || true)"
if [ -n "$DESKTOP" ]; then
  case "$OUTFMT" in
    deb|rpm) info "Has desktop launcher(s); the converted package will refresh the app menu automatically on install." ;;
    *)       info "Has desktop launcher(s); if the app menu doesn't show it after extracting, run: sudo update-desktop-database" ;;
  esac
  # Sanity-check launcher Exec= paths: absolute targets should exist in the
  # package (a broken Exec means a menu entry that silently does nothing)
  while IFS= read -r dfile; do
    [ -n "$dfile" ] || continue
    execbin="$(grep -m1 '^Exec=' "$dfile" | sed 's/^Exec=//; s/ .*//; s/"//g')"
    case "$execbin" in
      /*) [ -e "$STAGE$execbin" ] || warn "Launcher $(basename "$dfile") points to '$execbin', which is not in this package — the menu entry may not work." ;;
    esac
  done <<< "$DESKTOP"
fi

# --- 4. Format-specific notes ---
case "$INFMT" in
  snap)     warn "Snaps expect the snap runtime and hardcoded /snap paths; extracted apps often need tweaks to run standalone." ;;
  appimage) info "AppImages are self-contained; the extracted tree runs via its AppRun script." ;;
esac
case "$OUTFMT" in
  rpm) info "The rpm will be built with dependency auto-detection OFF so it installs cleanly." ;;
  deb) info "The deb will be built without a dependency list." ;;
esac
if [ "$TARGET_DISTRO" = "arch" ] && { [ "$OUTFMT" = "rpm" ] || [ "$OUTFMT" = "deb" ]; }; then
  info "Tip for Arch: consider '--to tar.gz' and extracting to /opt, or use 'debtap' from the AUR for native pacman packages."
fi

echo
if [ "$WARN_COUNT" -gt 0 ]; then
  echo "  Analysis found $WARN_COUNT potential issue(s) — see [!] items above."
else
  echo "  No blocking issues found."
fi
echo "======================================================="
echo
ANALYSIS_DONE=1

[ "$INFOONLY" = 1 ] && exit 0

# --- Confirm ---
if [ "$ASSUME_YES" = 0 ]; then
  read -rp "Proceed with conversion to $OUTFMT? [Y/n] " ans
  case "${ans:-y}" in y|Y|yes|YES) ;; *) echo "Aborted."; exit 0 ;; esac
fi

# =====================================================================
#                            BUILD OUTPUT
# =====================================================================
OUTBASE="${PKGNAME}-${PKGVER}.${PKGARCH}"

build_targz() {
  local out="${OUTBASE}.tar.gz"
  tar -czf "$out" -C "$STAGE" .
  echo "Created: $out"
  echo "  Extract anywhere:   tar -xzf $out"
  echo "  Or into system:     sudo tar -xzf $out -C /"
}

build_dir() {
  local out="${OUTBASE}.extracted"
  rm -rf "$out"; mkdir -p "$out"
  cp -a "$STAGE/." "$out/"
  echo "Created folder: $out/"
}

build_deb() {
  need dpkg-deb dpkg
  local d="$WORKDIR/debbuild"
  mkdir -p "$d"
  cp -a "$STAGE/." "$d/"
  rm -rf "$d/DEBIAN"; mkdir -p "$d/DEBIAN"
  local darch="$PKGARCH"
  case "$darch" in x86_64) darch=amd64 ;; aarch64) darch=arm64 ;; esac
  cat > "$d/DEBIAN/control" <<EOF
Package: $(echo "$PKGNAME" | tr 'A-Z_ ' 'a-z--')
Version: $PKGVER
Architecture: $darch
Maintainer: pkgconvert <none@localhost>
Description: ${DESC:-Converted package}
EOF
  # Desktop integration: if the app ships launchers or icons, add a
  # post-install script so they register in the menu automatically.
  if find "$STAGE" \( -name '*.desktop' -o -path '*icons*' \) -print -quit 2>/dev/null | grep -q .; then
    cat > "$d/DEBIAN/postinst" <<'EOF'
#!/bin/sh
set -e
command -v update-desktop-database >/dev/null 2>&1 && update-desktop-database -q /usr/share/applications || true
command -v gtk-update-icon-cache >/dev/null 2>&1 && gtk-update-icon-cache -qtf /usr/share/icons/hicolor 2>/dev/null || true
exit 0
EOF
    chmod 755 "$d/DEBIAN/postinst"
    cp "$d/DEBIAN/postinst" "$d/DEBIAN/postrm"
  fi
  local out="${OUTBASE}.deb"
  dpkg-deb --build --root-owner-group "$d" "$out" >/dev/null
  echo "Created: $out"
  echo "  Install with: sudo apt install ./$out"
}

build_rpm() {
  need rpmbuild rpm-build
  local top="$WORKDIR/rpmbuild"
  mkdir -p "$top"/{BUILD,RPMS,SPECS,SOURCES,BUILDROOT}
  local rname; rname="$(echo "$PKGNAME" | tr ' _' '--')"
  local spec="$top/SPECS/$rname.spec"
  # Desktop integration scriptlets, only when launchers/icons are present
  local POSTSECTION=""
  if find "$STAGE" \( -name '*.desktop' -o -path '*icons*' \) -print -quit 2>/dev/null | grep -q .; then
    POSTSECTION='
%post
command -v update-desktop-database >/dev/null 2>&1 && update-desktop-database -q /usr/share/applications || :
command -v gtk-update-icon-cache >/dev/null 2>&1 && gtk-update-icon-cache -qtf /usr/share/icons/hicolor 2>/dev/null || :

%postun
command -v update-desktop-database >/dev/null 2>&1 && update-desktop-database -q /usr/share/applications || :
command -v gtk-update-icon-cache >/dev/null 2>&1 && gtk-update-icon-cache -qtf /usr/share/icons/hicolor 2>/dev/null || :
'
  fi
  cat > "$spec" <<EOF
Name:           $rname
Version:        $(echo "$PKGVER" | tr '-' '.')
Release:        1
Summary:        ${DESC:-Converted package}
License:        Unknown
AutoReqProv:    no

%description
${DESC:-Converted with pkgconvert.}

%install
mkdir -p %{buildroot}
cp -a $STAGE/. %{buildroot}/

%files
/*
$POSTSECTION
EOF
  rpmbuild --define "_topdir $top" --target "$PKGARCH" -bb "$spec" >/dev/null 2>&1 \
    || rpmbuild --define "_topdir $top" -bb "$spec" >/dev/null
  local built
  built="$(find "$top/RPMS" -name '*.rpm' | head -n1)"
  [ -n "$built" ] || err -c 5 "rpmbuild produced no package"
  local out="${OUTBASE}.rpm"
  cp "$built" "$out"
  echo "Created: $out"
  case "$TARGET_DISTRO" in
    opensuse) echo "  Install with: sudo zypper install ./$out" ;;
    *)        echo "  Install with: sudo dnf install ./$out" ;;
  esac
}

case "$OUTFMT" in
  tar.gz|tgz) build_targz ;;
  deb)        build_deb ;;
  rpm)        build_rpm ;;
  dir)        build_dir ;;
  *) err -c 2 "Unknown output format: $OUTFMT (use tar.gz, deb, rpm, or dir)" ;;
esac
